# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8d46faf58c3dda30258417d775834e2cd5a4bf52ebf06ceebf1f3b9c6ee95079ba50476a2102a3f2cc878acd2dd890f82fc1d59d881a4424d328c1adb2b76f3

test:
  secret_key_base: f8af80a90c152711cfd02272c6d02cb247e87e8c4947a4880130ee2f3f1f2a6c9d43b77c653e84f2e224db0ed2640fad70170dd5380daf7eb5acc83a99207e88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
